TOP = ../..
include $(TOP)/mk/boilerplate.mk

SRC_HC_OPTS += -cpp -package old-time

# kLongLivedTreeDepth	  = 17 :: Int
# kArraySize	 	     = 500000 :: Int
# kMinTreeDepth 	     = 4 :: Int
# kMaxTreeDepth 	     = 17 :: Int

# NORM_OPTS = 17 500000 4 17
NORM_OPTS = 19 500000 5 20
SLOW_OPTS = 19 500000 6 20

include $(TOP)/mk/target.mk

