TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = anna fulsom gamteb \
          hpg pic \
          scs

# Omitted: 
#	HMMS	binary file endian-ness problems
OTHER_SUBDIRS = HMMS PolyGP ebnf2ps linear rx

include $(TOP)/mk/target.mk

