TOP = ../..
include $(TOP)/mk/boilerplate.mk

FAST_OPTS = -nt 8 -dt 6 -nv 15 -dv 8 -de 8
NORM_OPTS = -nt 14 -dt 10 -nv 58 -dv 10 -de 10
SLOW_OPTS = -nt 15 -dt 10 -nv 60 -dv 13 -de 14

include $(TOP)/mk/target.mk

