TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = atom boyer calendar circsim \
          clausify constraints cryptarithm2 \
          fft2 fibheaps gcd hartel integer knights lcss mandel \
          mandel2 multiplier power \
          rewrite simple sorting sphere

# compreals	no suitable test data
# salishan	no Haskell code!
OTHER_SUBDIRS = compreals lambda last-piece mate salishan secretary triangle

include $(TOP)/mk/target.mk

